srr_sample_file: '/data/swamyvs/scEiaD/data/sample_run_layout_organism_tech.tsv'
subset_clustering: 'False'
git_dir: '/data/swamyvs/scEiaD'
bustools_path: ''
working_dir: '/data/swamyvs/scEiaD'
conda_dir: '/data/swamyvs/anaconda3'
config_abspath: '/data/swamyvs/scEiaD/config.yaml'
fastq_path: '/data/OGVFB_BG/scEiaD'
fi_tsne_dir: '/data/swamyvs/scEiaD'
quant_path: '/data/OGVFB_BG/scEiaD'
