srr_sample_file: '/data/mcgaugheyd/scEiaD/data/sample_run_layout_organism_tech.tsv'
subset_clustering: 'False'
git_dir: '/data/mcgaugheyd/scEiaD'
bustools_path: '/data/mcgaugheyd/git/'
working_dir: '/data/mcgaugheyd/scEiaD'
conda_dir: ' /data/mcgaugheyd/conda/'
config_abspath: '/data/mcgaugheyd/scEiaD/config.yaml'
fastq_path: '/data/OGVFB_BG/scEiaD'
fi_tsne_dir: '/data/mcgaugheyd/scEiaD'
quant_path: '/data/OGVFB_BG/scEiaD/quant'
mso_umap_file: '/data/OGVFB_BG/scEiaD/umap/Mus_musculus_Macaca_fascicularis_Homo_sapiens__n_features5000__counts__TabulaDroplet__batch__scVI__dims8__preFilter__mindist0.1__nneighbors15.umapFilter.predictions.Rdata'
tabula_muris_comb: '/data/OGVFB_BG/scEiaD/tabula_muris_combined.Rdata'
cell_info: 'cell_info.tsv'
