srr_sample_file: '/data/swamyvs/scEiad_subcelltype/data/sample_run_layout_organism_tech.tsv'
subset_clustering: 'False'
git_dir: '/data/swamyvs/scEiad_subcelltype/'
bustools_path: '/data/swamyvs/scEiaD/bustools'
working_dir: '/data/swamyvs/scEiad_subcelltype/'
conda_dir: '/data/swamyvs/anaconda3'
config_abspath: '/data/swamyvs/scEiad_subcelltype/config.yaml'
fastq_path: '/data/OGVFB_BG/scEiaD'
fi_tsne_dir: '/data/swamyvs/scEiaD'
quant_path: '/data/swamyvs/scEiad_subcelltype'
mso_umap_file: '/data/OGVFB_BG/scEiaD/umap/Mus_musculus_Macaca_fascicularis_Homo_sapiens__n_features5000__counts__TabulaDroplet__batch__scVI__dims8__preFilter__mindist0.1__nneighbors15.umapFilter.predictions.Rdata'
tabula_muris_comb: '/data/OGVFB_BG/scEiaD/tabula_muris_combined.Rdata'
cell_info: 'pipeline_data/cell_info/all_cell_info.tsv'
integration_json: 'integration-config-subCellType.json'
rson_temp_dir: '/data/swamyvs/scEiad_subcelltype/rson_tmp/'
DNTX_gtf_path: '/data/swamyvs/ocular_transcriptomes_pipeline/data/gtf/all_tissue.combined_annotated.gtf'
samplename_patterns: 'references/samplename_patterns.txt'
